apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: cluster-infratwo
spec:
  name: cluster-infratwo
  detach: false
  type: TERRAFORM
  approval: true
  manageState: true
  actor: console@plural.sh
  configuration:
    version: '1.8'
  repositoryRef:
    name: infra
    namespace: infra
  clusterRef:
    name: mgmt
    namespace: infra
  variables:
    cluster: infratwo
    fleet: infra
    tier: prod
  
  git:
    ref: main
    folder: terraform/modules/clusters/aws
